// ============================================================
// SkyHigh Executive — Geo Dataset
// World countries (ISO lookup) | 68 airports | Mercator lat/lon
// ============================================================
window.SkyHigh = window.SkyHigh || {};

// ── FULL ISO 3166-1 NUMERIC COUNTRY LOOKUP ─────────────────
// Keys = numeric codes used by world-atlas topojson
// Covers all ~195 UN-recognized countries + territories in atlas
window.SkyHigh.WORLD_COUNTRIES = {
  4:   { name:'Afghanistan',                region:'Asia',           risk:'HIGH',   tier:'LOW',    emoji:'🇦🇫' },
  8:   { name:'Albania',                    region:'Europe',         risk:'MEDIUM', tier:'LOW',    emoji:'🇦🇱' },
  12:  { name:'Algeria',                    region:'Africa',         risk:'MEDIUM', tier:'MEDIUM', emoji:'🇩🇿' },
  24:  { name:'Angola',                     region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇦🇴' },
  32:  { name:'Argentina',                  region:'South America',  risk:'HIGH',   tier:'MEDIUM', emoji:'🇦🇷' },
  36:  { name:'Australia',                  region:'Asia Pacific',   risk:'LOW',    tier:'HIGH',   emoji:'🇦🇺' },
  40:  { name:'Austria',                    region:'Europe',         risk:'LOW',    tier:'HIGH',   emoji:'🇦🇹' },
  50:  { name:'Bangladesh',                 region:'Asia Pacific',   risk:'MEDIUM', tier:'MEDIUM', emoji:'🇧🇩' },
  56:  { name:'Belgium',                    region:'Europe',         risk:'LOW',    tier:'HIGH',   emoji:'🇧🇪' },
  64:  { name:'Bhutan',                     region:'Asia Pacific',   risk:'LOW',    tier:'LOW',    emoji:'🇧🇹' },
  68:  { name:'Bolivia',                    region:'South America',  risk:'MEDIUM', tier:'LOW',    emoji:'🇧🇴' },
  70:  { name:'Bosnia and Herzegovina',     region:'Europe',         risk:'MEDIUM', tier:'LOW',    emoji:'🇧🇦' },
  72:  { name:'Botswana',                   region:'Africa',         risk:'LOW',    tier:'LOW',    emoji:'🇧🇼' },
  76:  { name:'Brazil',                     region:'South America',  risk:'MEDIUM', tier:'HIGH',   emoji:'🇧🇷' },
  84:  { name:'Belize',                     region:'North America',  risk:'MEDIUM', tier:'LOW',    emoji:'🇧🇿' },
  96:  { name:'Brunei',                     region:'Asia Pacific',   risk:'LOW',    tier:'HIGH',   emoji:'🇧🇳' },
  100: { name:'Bulgaria',                   region:'Europe',         risk:'MEDIUM', tier:'MEDIUM', emoji:'🇧🇬' },
  104: { name:'Myanmar',                    region:'Asia Pacific',   risk:'HIGH',   tier:'LOW',    emoji:'🇲🇲' },
  108: { name:'Burundi',                    region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇧🇮' },
  116: { name:'Cambodia',                   region:'Asia Pacific',   risk:'MEDIUM', tier:'LOW',    emoji:'🇰🇭' },
  120: { name:'Cameroon',                   region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇨🇲' },
  124: { name:'Canada',                     region:'North America',  risk:'LOW',    tier:'HIGH',   emoji:'🇨🇦' },
  140: { name:'Central African Republic',   region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇨🇫' },
  144: { name:'Sri Lanka',                  region:'Asia Pacific',   risk:'MEDIUM', tier:'MEDIUM', emoji:'🇱🇰' },
  152: { name:'Chile',                      region:'South America',  risk:'MEDIUM', tier:'HIGH',   emoji:'🇨🇱' },
  156: { name:'China',                      region:'Asia Pacific',   risk:'MEDIUM', tier:'PREMIUM',emoji:'🇨🇳' },
  170: { name:'Colombia',                   region:'South America',  risk:'HIGH',   tier:'MEDIUM', emoji:'🇨🇴' },
  178: { name:'DR Congo',                   region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇨🇩' },
  180: { name:'Congo',                      region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇨🇬' },
  188: { name:'Costa Rica',                 region:'North America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇨🇷' },
  191: { name:'Croatia',                    region:'Europe',         risk:'LOW',    tier:'MEDIUM', emoji:'🇭🇷' },
  192: { name:'Cuba',                       region:'North America',  risk:'HIGH',   tier:'LOW',    emoji:'🇨🇺' },
  196: { name:'Cyprus',                     region:'Europe',         risk:'LOW',    tier:'MEDIUM', emoji:'🇨🇾' },
  203: { name:'Czech Republic',             region:'Europe',         risk:'LOW',    tier:'HIGH',   emoji:'🇨🇿' },
  208: { name:'Denmark',                    region:'Europe',         risk:'LOW',    tier:'HIGH',   emoji:'🇩🇰' },
  218: { name:'Ecuador',                    region:'South America',  risk:'MEDIUM', tier:'MEDIUM', emoji:'🇪🇨' },
  818: { name:'Egypt',                      region:'Africa',         risk:'MEDIUM', tier:'MEDIUM', emoji:'🇪🇬' },
  222: { name:'El Salvador',                region:'North America',  risk:'HIGH',   tier:'LOW',    emoji:'🇸🇻' },
  231: { name:'Ethiopia',                   region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇪🇹' },
  246: { name:'Finland',                    region:'Europe',         risk:'LOW',    tier:'HIGH',   emoji:'🇫🇮' },
  250: { name:'France',                     region:'Europe',         risk:'LOW',    tier:'PREMIUM',emoji:'🇫🇷' },
  266: { name:'Gabon',                      region:'Africa',         risk:'MEDIUM', tier:'LOW',    emoji:'🇬🇦' },
  276: { name:'Germany',                    region:'Europe',         risk:'LOW',    tier:'PREMIUM',emoji:'🇩🇪' },
  288: { name:'Ghana',                      region:'Africa',         risk:'MEDIUM', tier:'LOW',    emoji:'🇬🇭' },
  300: { name:'Greece',                     region:'Europe',         risk:'MEDIUM', tier:'HIGH',   emoji:'🇬🇷' },
  320: { name:'Guatemala',                  region:'North America',  risk:'HIGH',   tier:'LOW',    emoji:'🇬🇹' },
  324: { name:'Guinea',                     region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇬🇳' },
  332: { name:'Haiti',                      region:'North America',  risk:'HIGH',   tier:'LOW',    emoji:'🇭🇹' },
  340: { name:'Honduras',                   region:'North America',  risk:'HIGH',   tier:'LOW',    emoji:'🇭🇳' },
  348: { name:'Hungary',                    region:'Europe',         risk:'MEDIUM', tier:'MEDIUM', emoji:'🇭🇺' },
  356: { name:'India',                      region:'Asia Pacific',   risk:'MEDIUM', tier:'HIGH',   emoji:'🇮🇳' },
  360: { name:'Indonesia',                  region:'Asia Pacific',   risk:'MEDIUM', tier:'HIGH',   emoji:'🇮🇩' },
  364: { name:'Iran',                       region:'Middle East',    risk:'HIGH',   tier:'MEDIUM', emoji:'🇮🇷' },
  368: { name:'Iraq',                       region:'Middle East',    risk:'HIGH',   tier:'MEDIUM', emoji:'🇮🇶' },
  372: { name:'Ireland',                    region:'Europe',         risk:'LOW',    tier:'HIGH',   emoji:'🇮🇪' },
  376: { name:'Israel',                     region:'Middle East',    risk:'HIGH',   tier:'HIGH',   emoji:'🇮🇱' },
  380: { name:'Italy',                      region:'Europe',         risk:'MEDIUM', tier:'HIGH',   emoji:'🇮🇹' },
  388: { name:'Jamaica',                    region:'North America',  risk:'MEDIUM', tier:'MEDIUM', emoji:'🇯🇲' },
  392: { name:'Japan',                      region:'Asia Pacific',   risk:'LOW',    tier:'PREMIUM',emoji:'🇯🇵' },
  400: { name:'Jordan',                     region:'Middle East',    risk:'MEDIUM', tier:'MEDIUM', emoji:'🇯🇴' },
  398: { name:'Kazakhstan',                 region:'Asia Pacific',   risk:'MEDIUM', tier:'MEDIUM', emoji:'🇰🇿' },
  404: { name:'Kenya',                      region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇰🇪' },
  408: { name:'North Korea',                region:'Asia Pacific',   risk:'HIGH',   tier:'LOW',    emoji:'🇰🇵' },
  410: { name:'South Korea',                region:'Asia Pacific',   risk:'LOW',    tier:'HIGH',   emoji:'🇰🇷' },
  414: { name:'Kuwait',                     region:'Middle East',    risk:'LOW',    tier:'HIGH',   emoji:'🇰🇼' },
  418: { name:'Laos',                       region:'Asia Pacific',   risk:'MEDIUM', tier:'LOW',    emoji:'🇱🇦' },
  422: { name:'Lebanon',                    region:'Middle East',    risk:'HIGH',   tier:'MEDIUM', emoji:'🇱🇧' },
  426: { name:'Lesotho',                    region:'Africa',         risk:'MEDIUM', tier:'LOW',    emoji:'🇱🇸' },
  430: { name:'Liberia',                    region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇱🇷' },
  434: { name:'Libya',                      region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇱🇾' },
  440: { name:'Lithuania',                  region:'Europe',         risk:'LOW',    tier:'MEDIUM', emoji:'🇱🇹' },
  442: { name:'Luxembourg',                 region:'Europe',         risk:'LOW',    tier:'PREMIUM',emoji:'🇱🇺' },
  450: { name:'Madagascar',                 region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇲🇬' },
  454: { name:'Malawi',                     region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇲🇼' },
  458: { name:'Malaysia',                   region:'Asia Pacific',   risk:'MEDIUM', tier:'HIGH',   emoji:'🇲🇾' },
  466: { name:'Mali',                       region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇲🇱' },
  484: { name:'Mexico',                     region:'North America',  risk:'MEDIUM', tier:'MEDIUM', emoji:'🇲🇽' },
  496: { name:'Mongolia',                   region:'Asia Pacific',   risk:'MEDIUM', tier:'LOW',    emoji:'🇲🇳' },
  504: { name:'Morocco',                    region:'Africa',         risk:'MEDIUM', tier:'LOW',    emoji:'🇲🇦' },
  508: { name:'Mozambique',                 region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇲🇿' },
  516: { name:'Namibia',                    region:'Africa',         risk:'MEDIUM', tier:'LOW',    emoji:'🇳🇦' },
  524: { name:'Nepal',                      region:'Asia Pacific',   risk:'MEDIUM', tier:'LOW',    emoji:'🇳🇵' },
  528: { name:'Netherlands',                region:'Europe',         risk:'LOW',    tier:'PREMIUM',emoji:'🇳🇱' },
  540: { name:'New Caledonia',              region:'Asia Pacific',   risk:'LOW',    tier:'MEDIUM', emoji:'🇳🇨' },
  554: { name:'New Zealand',                region:'Asia Pacific',   risk:'LOW',    tier:'HIGH',   emoji:'🇳🇿' },
  558: { name:'Nicaragua',                  region:'North America',  risk:'HIGH',   tier:'LOW',    emoji:'🇳🇮' },
  562: { name:'Niger',                      region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇳🇪' },
  566: { name:'Nigeria',                    region:'Africa',         risk:'HIGH',   tier:'MEDIUM', emoji:'🇳🇬' },
  578: { name:'Norway',                     region:'Europe',         risk:'LOW',    tier:'HIGH',   emoji:'🇳🇴' },
  586: { name:'Pakistan',                   region:'Asia Pacific',   risk:'HIGH',   tier:'MEDIUM', emoji:'🇵🇰' },
  591: { name:'Panama',                     region:'North America',  risk:'MEDIUM', tier:'MEDIUM', emoji:'🇵🇦' },
  598: { name:'Papua New Guinea',           region:'Asia Pacific',   risk:'HIGH',   tier:'LOW',    emoji:'🇵🇬' },
  600: { name:'Paraguay',                   region:'South America',  risk:'MEDIUM', tier:'LOW',    emoji:'🇵🇾' },
  604: { name:'Peru',                       region:'South America',  risk:'MEDIUM', tier:'MEDIUM', emoji:'🇵🇪' },
  608: { name:'Philippines',                region:'Asia Pacific',   risk:'HIGH',   tier:'MEDIUM', emoji:'🇵🇭' },
  616: { name:'Poland',                     region:'Europe',         risk:'LOW',    tier:'MEDIUM', emoji:'🇵🇱' },
  620: { name:'Portugal',                   region:'Europe',         risk:'LOW',    tier:'HIGH',   emoji:'🇵🇹' },
  630: { name:'Puerto Rico',                region:'North America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇵🇷' },
  642: { name:'Romania',                    region:'Europe',         risk:'MEDIUM', tier:'MEDIUM', emoji:'🇷🇴' },
  643: { name:'Russia',                     region:'Europe',         risk:'HIGH',   tier:'MEDIUM', emoji:'🇷🇺' },
  646: { name:'Rwanda',                     region:'Africa',         risk:'MEDIUM', tier:'LOW',    emoji:'🇷🇼' },
  682: { name:'Saudi Arabia',               region:'Middle East',    risk:'LOW',    tier:'HIGH',   emoji:'🇸🇦' },
  686: { name:'Senegal',                    region:'Africa',         risk:'MEDIUM', tier:'LOW',    emoji:'🇸🇳' },
  694: { name:'Sierra Leone',               region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇸🇱' },
  703: { name:'Slovakia',                   region:'Europe',         risk:'LOW',    tier:'MEDIUM', emoji:'🇸🇰' },
  705: { name:'Slovenia',                   region:'Europe',         risk:'LOW',    tier:'MEDIUM', emoji:'🇸🇮' },
  706: { name:'Somalia',                    region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇸🇴' },
  710: { name:'South Africa',               region:'Africa',         risk:'HIGH',   tier:'MEDIUM', emoji:'🇿🇦' },
  716: { name:'Zimbabwe',                   region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇿🇼' },
  724: { name:'Spain',                      region:'Europe',         risk:'LOW',    tier:'HIGH',   emoji:'🇪🇸' },
  728: { name:'South Sudan',                region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇸🇸' },
  729: { name:'Sudan',                      region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇸🇩' },
  740: { name:'Suriname',                   region:'South America',  risk:'MEDIUM', tier:'LOW',    emoji:'🇸🇷' },
  752: { name:'Sweden',                     region:'Europe',         risk:'LOW',    tier:'HIGH',   emoji:'🇸🇪' },
  756: { name:'Switzerland',                region:'Europe',         risk:'LOW',    tier:'PREMIUM',emoji:'🇨🇭' },
  760: { name:'Syria',                      region:'Middle East',    risk:'HIGH',   tier:'LOW',    emoji:'🇸🇾' },
  158: { name:'Taiwan',                     region:'Asia Pacific',   risk:'MEDIUM', tier:'HIGH',   emoji:'🇹🇼' },
  762: { name:'Tajikistan',                 region:'Asia Pacific',   risk:'HIGH',   tier:'LOW',    emoji:'🇹🇯' },
  764: { name:'Thailand',                   region:'Asia Pacific',   risk:'MEDIUM', tier:'HIGH',   emoji:'🇹🇭' },
  768: { name:'Togo',                       region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇹🇬' },
  780: { name:'Trinidad and Tobago',        region:'North America',  risk:'MEDIUM', tier:'MEDIUM', emoji:'🇹🇹' },
  788: { name:'Tunisia',                    region:'Africa',         risk:'MEDIUM', tier:'MEDIUM', emoji:'🇹🇳' },
  792: { name:'Turkey',                     region:'Europe',         risk:'MEDIUM', tier:'HIGH',   emoji:'🇹🇷' },
  800: { name:'Uganda',                     region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇺🇬' },
  804: { name:'Ukraine',                    region:'Europe',         risk:'HIGH',   tier:'MEDIUM', emoji:'🇺🇦' },
  784: { name:'United Arab Emirates',       region:'Middle East',    risk:'LOW',    tier:'PREMIUM',emoji:'🇦🇪' },
  826: { name:'United Kingdom',             region:'Europe',         risk:'LOW',    tier:'PREMIUM',emoji:'🇬🇧' },
  840: { name:'United States',              region:'North America',  risk:'LOW',    tier:'PREMIUM',emoji:'🇺🇸' },
  858: { name:'Uruguay',                    region:'South America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇺🇾' },
  860: { name:'Uzbekistan',                 region:'Asia Pacific',   risk:'MEDIUM', tier:'LOW',    emoji:'🇺🇿' },
  862: { name:'Venezuela',                  region:'South America',  risk:'HIGH',   tier:'MEDIUM', emoji:'🇻🇪' },
  704: { name:'Vietnam',                    region:'Asia Pacific',   risk:'MEDIUM', tier:'MEDIUM', emoji:'🇻🇳' },
  887: { name:'Yemen',                      region:'Middle East',    risk:'HIGH',   tier:'LOW',    emoji:'🇾🇪' },
  894: { name:'Zambia',                     region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇿🇲' },
  // Additional territories / smaller nations in atlas
  16:  { name:'American Samoa',             region:'Asia Pacific',   risk:'LOW',    tier:'LOW',    emoji:'🇦🇸' },
  533: { name:'Aruba',                      region:'North America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇦🇼' },
  44:  { name:'Bahamas',                    region:'North America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇧🇸' },
  48:  { name:'Bahrain',                    region:'Middle East',    risk:'LOW',    tier:'HIGH',   emoji:'🇧🇭' },
  52:  { name:'Barbados',                   region:'North America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇧🇧' },
  112: { name:'Belarus',                    region:'Europe',         risk:'HIGH',   tier:'MEDIUM', emoji:'🇧🇾' },
  204: { name:'Benin',                      region:'Africa',         risk:'MEDIUM', tier:'LOW',    emoji:'🇧🇯' },
  60:  { name:'Bermuda',                    region:'North America',  risk:'LOW',    tier:'HIGH',   emoji:'🇧🇲' },
  148: { name:'Chad',                       region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇹🇩' },
  174: { name:'Comoros',                    region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇰🇲' },
  384: { name:'Ivory Coast',                region:'Africa',         risk:'MEDIUM', tier:'LOW',    emoji:'🇨🇮' },
  214: { name:'Dominican Republic',         region:'North America',  risk:'MEDIUM', tier:'MEDIUM', emoji:'🇩🇴' },
  232: { name:'Eritrea',                    region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇪🇷' },
  233: { name:'Estonia',                    region:'Europe',         risk:'LOW',    tier:'MEDIUM', emoji:'🇪🇪' },
  238: { name:'Falkland Islands',           region:'South America',  risk:'LOW',    tier:'LOW',    emoji:'🇫🇰' },
  242: { name:'Fiji',                       region:'Asia Pacific',   risk:'MEDIUM', tier:'LOW',    emoji:'🇫🇯' },
  260: { name:'French Guiana',              region:'South America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇬🇫' },
  308: { name:'Grenada',                    region:'North America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇬🇩' },
  312: { name:'Guadeloupe',                 region:'North America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇬🇵' },
  316: { name:'Guam',                       region:'Asia Pacific',   risk:'LOW',    tier:'MEDIUM', emoji:'🇬🇺' },
  328: { name:'Guyana',                     region:'South America',  risk:'HIGH',   tier:'LOW',    emoji:'🇬🇾' },
  352: { name:'Iceland',                    region:'Europe',         risk:'LOW',    tier:'HIGH',   emoji:'🇮🇸' },
  388: { name:'Jamaica',                    region:'North America',  risk:'MEDIUM', tier:'MEDIUM', emoji:'🇯🇲' },
  417: { name:'Kyrgyzstan',                 region:'Asia Pacific',   risk:'MEDIUM', tier:'LOW',    emoji:'🇰🇬' },
  428: { name:'Latvia',                     region:'Europe',         risk:'LOW',    tier:'MEDIUM', emoji:'🇱🇻' },
  430: { name:'Liberia',                    region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇱🇷' },
  807: { name:'North Macedonia',            region:'Europe',         risk:'MEDIUM', tier:'LOW',    emoji:'🇲🇰' },
  474: { name:'Martinique',                 region:'North America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇲🇶' },
  478: { name:'Mauritania',                 region:'Africa',         risk:'HIGH',   tier:'LOW',    emoji:'🇲🇷' },
  480: { name:'Mauritius',                  region:'Africa',         risk:'LOW',    tier:'HIGH',   emoji:'🇲🇺' },
  484: { name:'Mexico',                     region:'North America',  risk:'MEDIUM', tier:'MEDIUM', emoji:'🇲🇽' },
  498: { name:'Moldova',                    region:'Europe',         risk:'MEDIUM', tier:'LOW',    emoji:'🇲🇩' },
  504: { name:'Morocco',                    region:'Africa',         risk:'MEDIUM', tier:'LOW',    emoji:'🇲🇦' },
  512: { name:'Oman',                       region:'Middle East',    risk:'LOW',    tier:'HIGH',   emoji:'🇴🇲' },
  585: { name:'Palau',                      region:'Asia Pacific',   risk:'LOW',    tier:'LOW',    emoji:'🇵🇼' },
  275: { name:'Palestine',                  region:'Middle East',    risk:'HIGH',   tier:'LOW',    emoji:'🇵🇸' },
  634: { name:'Qatar',                      region:'Middle East',    risk:'LOW',    tier:'PREMIUM',emoji:'🇶🇦' },
  638: { name:'Réunion',                    region:'Africa',         risk:'LOW',    tier:'MEDIUM', emoji:'🇷🇪' },
  659: { name:'Saint Kitts and Nevis',      region:'North America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇰🇳' },
  662: { name:'Saint Lucia',                region:'North America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇱🇨' },
  670: { name:'Saint Vincent',              region:'North America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇻🇨' },
  882: { name:'Samoa',                      region:'Asia Pacific',   risk:'LOW',    tier:'LOW',    emoji:'🇼🇸' },
  678: { name:'São Tomé and Príncipe',      region:'Africa',         risk:'LOW',    tier:'LOW',    emoji:'🇸🇹' },
  690: { name:'Seychelles',                 region:'Africa',         risk:'LOW',    tier:'HIGH',   emoji:'🇸🇨' },
  702: { name:'Singapore',                  region:'Asia Pacific',   risk:'LOW',    tier:'PREMIUM',emoji:'🇸🇬' },
  90:  { name:'Solomon Islands',            region:'Asia Pacific',   risk:'HIGH',   tier:'LOW',    emoji:'🇸🇧' },
  196: { name:'Cyprus',                     region:'Europe',         risk:'LOW',    tier:'MEDIUM', emoji:'🇨🇾' },
  776: { name:'Tonga',                      region:'Asia Pacific',   risk:'LOW',    tier:'LOW',    emoji:'🇹🇴' },
  626: { name:'Timor-Leste',                region:'Asia Pacific',   risk:'HIGH',   tier:'LOW',    emoji:'🇹🇱' },
  795: { name:'Turkmenistan',               region:'Asia Pacific',   risk:'HIGH',   tier:'LOW',    emoji:'🇹🇲' },
  798: { name:'Tuvalu',                     region:'Asia Pacific',   risk:'LOW',    tier:'LOW',    emoji:'🇹🇻' },
  548: { name:'Vanuatu',                    region:'Asia Pacific',   risk:'MEDIUM', tier:'LOW',    emoji:'🇻🇺' },
  659: { name:'Saint Kitts',                region:'North America',  risk:'LOW',    tier:'MEDIUM', emoji:'🇰🇳' },
  10:  { name:'Antarctica',                 region:'Other',          risk:'LOW',    tier:'LOW',    emoji:'🇦🇶' },
};

// Helper: get country info by ISO numeric id
window.SkyHigh.getWorldCountry = function(numericId) {
  const id = parseInt(numericId);
  return SkyHigh.WORLD_COUNTRIES[id] || { name: `Country #${id}`, region: 'Unknown', risk: 'MEDIUM', tier: 'MEDIUM', emoji: '🌍' };
};

window.SkyHigh.MAP_DATA = {

  // ── AIRPORTS ──────────────────────────────────────────────
  // hubLevel 1-5 (5=mega hub), demand 1000-10000 pax/quarter
  airports: [
    // North America
    { id:'JFK', countryIso:840, city:'New York',     name:'John F. Kennedy',        lat:40.64, lon:-73.78, hubLevel:5, demand:9500, demandProfile:'ULTRA_HIGH' },
    { id:'LAX', countryIso:840, city:'Los Angeles',  name:'Los Angeles Intl',       lat:33.94, lon:-118.41,hubLevel:5, demand:8800, demandProfile:'MEGA_VOLUME' },
    { id:'ORD', countryIso:840, city:'Chicago',      name:"O'Hare Intl",            lat:41.98, lon:-87.90, hubLevel:4, demand:7200, demandProfile:'HIGH_VOLUME' },
    { id:'MIA', countryIso:840, city:'Miami',        name:'Miami Intl',             lat:25.79, lon:-80.29, hubLevel:4, demand:6400, demandProfile:'TRANSIT_HUB' },
    { id:'YYZ', countryIso:124, city:'Toronto',      name:'Pearson Intl',           lat:43.68, lon:-79.63, hubLevel:4, demand:5800, demandProfile:'BUSINESS' },
    { id:'YVR', countryIso:124, city:'Vancouver',    name:'Vancouver Intl',         lat:49.19, lon:-123.18,hubLevel:3, demand:4200, demandProfile:'MIXED' },
    { id:'MEX', countryIso:484, city:'Mexico City',  name:'Benito Juárez Intl',     lat:19.44, lon:-99.07, hubLevel:4, demand:5200, demandProfile:'LARGE_DOMESTIC' },
    { id:'CUN', countryIso:484, city:'Cancún',       name:'Cancún Intl',            lat:21.04, lon:-86.87, hubLevel:3, demand:4800, demandProfile:'LEISURE_SURGE' },
    // Europe
    { id:'LHR', countryIso:826, city:'London',       name:'Heathrow',               lat:51.47, lon:-0.46,  hubLevel:5, demand:9200, demandProfile:'ULTRA_HIGH' },
    { id:'MAN', countryIso:826, city:'Manchester',   name:'Manchester Airport',     lat:53.35, lon:-2.27,  hubLevel:3, demand:3800, demandProfile:'BUSINESS' },
    { id:'CDG', countryIso:250, city:'Paris',        name:'Charles de Gaulle',      lat:49.01, lon:2.55,   hubLevel:5, demand:8900, demandProfile:'MEGA_VOLUME' },
    { id:'ORY', countryIso:250, city:'Paris',        name:'Paris Orly',             lat:48.73, lon:2.36,   hubLevel:3, demand:4100, demandProfile:'TOURISM' },
    { id:'FRA', countryIso:276, city:'Frankfurt',    name:'Frankfurt Airport',      lat:50.03, lon:8.57,   hubLevel:5, demand:8400, demandProfile:'HIGH_YIELD' },
    { id:'MUC', countryIso:276, city:'Munich',       name:'Munich Airport',         lat:48.35, lon:11.79,  hubLevel:4, demand:5600, demandProfile:'BUSINESS' },
    { id:'MAD', countryIso:724, city:'Madrid',       name:'Adolfo Suárez',          lat:40.49, lon:-3.57,  hubLevel:4, demand:6200, demandProfile:'TOURISM' },
    { id:'BCN', countryIso:724, city:'Barcelona',    name:'El Prat',                lat:41.30, lon:2.08,   hubLevel:4, demand:5900, demandProfile:'TOURISM' },
    { id:'FCO', countryIso:380, city:'Rome',         name:'Leonardo da Vinci',      lat:41.80, lon:12.25,  hubLevel:4, demand:5400, demandProfile:'TOURISM' },
    { id:'MXP', countryIso:380, city:'Milan',        name:'Malpensa Airport',       lat:45.62, lon:8.72,   hubLevel:3, demand:4600, demandProfile:'BUSINESS' },
    { id:'AMS', countryIso:528, city:'Amsterdam',    name:'Amsterdam Schiphol',     lat:52.31, lon:4.76,   hubLevel:5, demand:8100, demandProfile:'TRANSIT_HUB' },
    { id:'IST', countryIso:792, city:'Istanbul',     name:'Istanbul Airport',       lat:41.27, lon:28.74,  hubLevel:5, demand:8700, demandProfile:'TRANSIT_HUB' },
    { id:'AYT', countryIso:792, city:'Antalya',      name:'Antalya Airport',        lat:36.89, lon:30.79,  hubLevel:3, demand:4300, demandProfile:'LEISURE_SURGE' },
    { id:'ARN', countryIso:752, city:'Stockholm',    name:'Arlanda Airport',        lat:59.65, lon:17.92,  hubLevel:3, demand:3600, demandProfile:'BUSINESS' },
    { id:'WAW', countryIso:616, city:'Warsaw',       name:'Chopin Airport',         lat:52.17, lon:20.97,  hubLevel:3, demand:3400, demandProfile:'GROWING' },
    { id:'SVO', countryIso:643, city:'Moscow',       name:'Sheremetyevo Intl',      lat:55.97, lon:37.41,  hubLevel:4, demand:5500, demandProfile:'LARGE_DOMESTIC' },
    { id:'LED', countryIso:643, city:'St Petersburg',name:'Pulkovo Airport',        lat:59.80, lon:30.26,  hubLevel:3, demand:2800, demandProfile:'TOURISM' },
    // Middle East
    { id:'DXB', countryIso:784, city:'Dubai',        name:'Dubai Intl',             lat:25.25, lon:55.37,  hubLevel:5, demand:9800, demandProfile:'ULTRA_HIGH' },
    { id:'AUH', countryIso:784, city:'Abu Dhabi',    name:'Zayed Intl',             lat:24.44, lon:54.65,  hubLevel:4, demand:5900, demandProfile:'BUSINESS' },
    { id:'RUH', countryIso:682, city:'Riyadh',       name:'King Khalid Intl',       lat:24.96, lon:46.70,  hubLevel:4, demand:5600, demandProfile:'BUSINESS' },
    { id:'JED', countryIso:682, city:'Jeddah',       name:'King Abdulaziz Intl',    lat:21.67, lon:39.15,  hubLevel:4, demand:5800, demandProfile:'HIGH_VOLUME' },
    { id:'DOH', countryIso:634, city:'Doha',         name:'Hamad Intl',             lat:25.27, lon:51.61,  hubLevel:5, demand:7400, demandProfile:'TRANSIT_HUB' },
    { id:'CAI', countryIso:818, city:'Cairo',        name:'Cairo Intl',             lat:30.11, lon:31.41,  hubLevel:3, demand:4100, demandProfile:'MIXED' },
    // Africa
    { id:'JNB', countryIso:710, city:'Johannesburg', name:'O.R. Tambo Intl',        lat:-26.13,lon:28.24,  hubLevel:4, demand:5200, demandProfile:'HIGH_VOLUME' },
    { id:'CPT', countryIso:710, city:'Cape Town',    name:'Cape Town Intl',         lat:-33.97,lon:18.60,  hubLevel:3, demand:3800, demandProfile:'TOURISM' },
    { id:'LOS', countryIso:566, city:'Lagos',        name:'Murtala Muhammed Intl',  lat:6.58,  lon:3.32,   hubLevel:3, demand:3600, demandProfile:'EMERGING' },
    { id:'NBO', countryIso:404, city:'Nairobi',      name:'Jomo Kenyatta Intl',     lat:-1.32, lon:36.93,  hubLevel:3, demand:3200, demandProfile:'TRANSIT_HUB' },
    { id:'ADD', countryIso:231, city:'Addis Ababa',  name:'Bole Intl',              lat:8.98,  lon:38.80,  hubLevel:3, demand:2900, demandProfile:'EMERGING' },
    { id:'CMN', countryIso:504, city:'Casablanca',   name:'Mohammed V Intl',        lat:33.37, lon:-7.59,  hubLevel:3, demand:2800, demandProfile:'MIXED' },
    // Asia Pacific
    { id:'PEK', countryIso:156, city:'Beijing',      name:'Capital Intl',           lat:40.07, lon:116.60, hubLevel:5, demand:9100, demandProfile:'MEGA_VOLUME' },
    { id:'PVG', countryIso:156, city:'Shanghai',     name:'Pudong Intl',            lat:31.15, lon:121.81, hubLevel:5, demand:8800, demandProfile:'MEGA_VOLUME' },
    { id:'CAN', countryIso:156, city:'Guangzhou',    name:'Baiyun Intl',            lat:23.39, lon:113.30, hubLevel:4, demand:7200, demandProfile:'HIGH_VOLUME' },
    { id:'NRT', countryIso:392, city:'Tokyo',        name:'Narita Intl',            lat:35.77, lon:140.39, hubLevel:5, demand:8200, demandProfile:'ULTRA_HIGH' },
    { id:'HND', countryIso:392, city:'Tokyo',        name:'Haneda Airport',         lat:35.55, lon:139.78, hubLevel:5, demand:7900, demandProfile:'HIGH_YIELD' },
    { id:'KIX', countryIso:392, city:'Osaka',        name:'Kansai Intl',            lat:34.42, lon:135.24, hubLevel:4, demand:5600, demandProfile:'TOURISM' },
    { id:'ICN', countryIso:410, city:'Seoul',        name:'Incheon Intl',           lat:37.46, lon:126.44, hubLevel:5, demand:7800, demandProfile:'TRANSIT_HUB' },
    { id:'SIN', countryIso:702, city:'Singapore',    name:'Changi Airport',         lat:1.36,  lon:103.99, hubLevel:5, demand:8600, demandProfile:'TRANSIT_HUB' },
    { id:'DEL', countryIso:356, city:'New Delhi',    name:'Indira Gandhi Intl',     lat:28.56, lon:77.10,  hubLevel:5, demand:7400, demandProfile:'MEGA_VOLUME' },
    { id:'BOM', countryIso:356, city:'Mumbai',       name:'Chhatrapati Shivaji Intl',lat:19.09,lon:72.87,  hubLevel:5, demand:7100, demandProfile:'LARGE_DOMESTIC' },
    { id:'BLR', countryIso:356, city:'Bangalore',    name:'Kempegowda Intl',        lat:13.20, lon:77.71,  hubLevel:4, demand:5200, demandProfile:'TECH_BUSINESS' },
    { id:'BKK', countryIso:764, city:'Bangkok',      name:'Suvarnabhumi Airport',   lat:13.68, lon:100.75, hubLevel:5, demand:7200, demandProfile:'TRANSIT_HUB' },
    { id:'HKT', countryIso:764, city:'Phuket',       name:'Phuket Intl',            lat:8.11,  lon:98.30,  hubLevel:3, demand:4600, demandProfile:'LEISURE_SURGE' },
    { id:'CGK', countryIso:360, city:'Jakarta',      name:'Soekarno-Hatta Intl',    lat:-6.12, lon:106.66, hubLevel:4, demand:6200, demandProfile:'LARGE_DOMESTIC' },
    { id:'DPS', countryIso:360, city:'Bali',         name:'Ngurah Rai Intl',        lat:-8.75, lon:115.17, hubLevel:3, demand:5100, demandProfile:'TOURISM' },
    { id:'KUL', countryIso:458, city:'Kuala Lumpur', name:'KL Intl Airport',        lat:2.74,  lon:101.70, hubLevel:4, demand:6400, demandProfile:'TRANSIT_HUB' },
    { id:'MNL', countryIso:608, city:'Manila',       name:'Ninoy Aquino Intl',      lat:14.51, lon:121.02, hubLevel:4, demand:5600, demandProfile:'LARGE_DOMESTIC' },
    { id:'HAN', countryIso:704, city:'Hanoi',        name:'Noi Bai Intl',           lat:21.22, lon:105.81, hubLevel:3, demand:3800, demandProfile:'GROWING' },
    { id:'SGN', countryIso:704, city:'Ho Chi Minh City',name:'Tan Son Nhat Intl',   lat:10.82, lon:106.65, hubLevel:3, demand:4200, demandProfile:'GROWING' },
    { id:'SYD', countryIso:36,  city:'Sydney',       name:'Kingsford Smith',        lat:-33.94,lon:151.18, hubLevel:5, demand:6800, demandProfile:'MIXED' },
    { id:'MEL', countryIso:36,  city:'Melbourne',    name:'Tullamarine Airport',    lat:-37.67,lon:144.84, hubLevel:4, demand:5400, demandProfile:'BUSINESS' },
    // South America
    { id:'GRU', countryIso:76,  city:'São Paulo',    name:'Guarulhos Intl',         lat:-23.43,lon:-46.47, hubLevel:5, demand:7200, demandProfile:'MEGA_VOLUME' },
    { id:'GIG', countryIso:76,  city:'Rio de Janeiro',name:'Galeão Intl',           lat:-22.81,lon:-43.25, hubLevel:4, demand:5400, demandProfile:'TOURISM' },
    { id:'EZE', countryIso:32,  city:'Buenos Aires', name:'Ministro Pistarini',     lat:-34.82,lon:-58.54, hubLevel:3, demand:4100, demandProfile:'BUSINESS' },
    { id:'BOG', countryIso:170, city:'Bogotá',       name:'El Dorado Intl',         lat:4.70,  lon:-74.14, hubLevel:3, demand:4300, demandProfile:'EMERGING' },
    { id:'SCL', countryIso:152, city:'Santiago',     name:'Arturo Merino Benítez',  lat:-33.39,lon:-70.79, hubLevel:3, demand:4000, demandProfile:'BUSINESS' },
    { id:'LIM', countryIso:604, city:'Lima',         name:'Jorge Chávez Intl',      lat:-12.02,lon:-77.11, hubLevel:3, demand:3700, demandProfile:'GROWING' },
    { id:'UIO', countryIso:218, city:'Quito',        name:'Mariscal Sucre Intl',    lat:-0.13, lon:-78.36, hubLevel:2, demand:2400, demandProfile:'EMERGING' },
    { id:'MVD', countryIso:858, city:'Montevideo',   name:'Carrasco Intl',          lat:-34.84,lon:-56.03, hubLevel:2, demand:2000, demandProfile:'BUSINESS' },
    { id:'ASU', countryIso:600, city:'Asunción',     name:'Silvio Pettirossi Intl', lat:-25.24,lon:-57.52, hubLevel:2, demand:1700, demandProfile:'EMERGING' },
    { id:'CCS', countryIso:862, city:'Caracas',      name:'Simón Bolívar Intl',     lat:10.60, lon:-66.99, hubLevel:3, demand:2600, demandProfile:'VOLATILE' },
    { id:'LPB', countryIso:68,  city:'La Paz',       name:'El Alto Intl',           lat:-16.51,lon:-68.19, hubLevel:2, demand:1800, demandProfile:'EMERGING' },
    { id:'SSA', countryIso:76,  city:'Salvador',     name:'Deputado Luís Eduardo',  lat:-12.91,lon:-38.33, hubLevel:2, demand:2200, demandProfile:'TOURISM' },
    { id:'FOR', countryIso:76,  city:'Fortaleza',    name:'Pinto Martins Intl',     lat:-3.78, lon:-38.53, hubLevel:2, demand:2100, demandProfile:'TOURISM' },
    { id:'GYE', countryIso:218, city:'Guayaquil',    name:'José Joaquín de Olmedo', lat:-2.16, lon:-79.88, hubLevel:2, demand:1900, demandProfile:'EMERGING' },
    // North America — extended
    { id:'DFW', countryIso:840, city:'Dallas',       name:'Dallas Fort Worth Intl', lat:32.90, lon:-97.04, hubLevel:5, demand:8600, demandProfile:'BUSINESS' },
    { id:'ATL', countryIso:840, city:'Atlanta',      name:'Hartsfield-Jackson Intl',lat:33.64, lon:-84.44, hubLevel:5, demand:9000, demandProfile:'HIGH_VOLUME' },
    { id:'SFO', countryIso:840, city:'San Francisco',name:'San Francisco Intl',     lat:37.62, lon:-122.38,hubLevel:4, demand:7200, demandProfile:'TECH_BUSINESS' },
    { id:'SEA', countryIso:840, city:'Seattle',      name:'Seattle-Tacoma Intl',    lat:47.45, lon:-122.31,hubLevel:4, demand:6200, demandProfile:'TECH_BUSINESS' },
    { id:'BOS', countryIso:840, city:'Boston',       name:'Logan Intl',             lat:42.37, lon:-71.00, hubLevel:4, demand:5800, demandProfile:'BUSINESS' },
    { id:'DEN', countryIso:840, city:'Denver',       name:'Denver Intl',            lat:39.86, lon:-104.67,hubLevel:4, demand:5500, demandProfile:'MIXED' },
    { id:'LAS', countryIso:840, city:'Las Vegas',    name:'Harry Reid Intl',        lat:36.08, lon:-115.15,hubLevel:3, demand:5200, demandProfile:'LEISURE_SURGE' },
    { id:'MSP', countryIso:840, city:'Minneapolis',  name:'Minneapolis-St Paul Intl',lat:44.88,lon:-93.22, hubLevel:3, demand:4400, demandProfile:'BUSINESS' },
    { id:'PHX', countryIso:840, city:'Phoenix',      name:'Sky Harbor Intl',        lat:33.44, lon:-112.01,hubLevel:3, demand:4600, demandProfile:'MIXED' },
    { id:'DTW', countryIso:840, city:'Detroit',      name:'Detroit Metro Wayne',    lat:42.21, lon:-83.35, hubLevel:3, demand:4100, demandProfile:'BUSINESS' },
    { id:'GUA', countryIso:320, city:'Guatemala City',name:'La Aurora Intl',        lat:14.58, lon:-90.53, hubLevel:2, demand:2000, demandProfile:'EMERGING' },
    { id:'SJO', countryIso:188, city:'San José',     name:'Juan Santamaría Intl',   lat:9.99,  lon:-84.21, hubLevel:2, demand:2200, demandProfile:'TOURISM' },
    { id:'PTY', countryIso:591, city:'Panama City',  name:'Tocumen Intl',           lat:9.07,  lon:-79.38, hubLevel:3, demand:3400, demandProfile:'TRANSIT_HUB' },
    { id:'SJU', countryIso:630, city:'San Juan',     name:'Luis Muñoz Marín Intl',  lat:18.44, lon:-66.00, hubLevel:3, demand:3100, demandProfile:'TOURISM' },
    { id:'SDQ', countryIso:214, city:'Santo Domingo',name:'Las Américas Intl',      lat:18.43, lon:-69.67, hubLevel:2, demand:2800, demandProfile:'TOURISM' },
    { id:'NAS', countryIso:44,  city:'Nassau',       name:'Lynden Pindling Intl',   lat:25.04, lon:-77.47, hubLevel:2, demand:2400, demandProfile:'TOURISM' },
    { id:'MBJ', countryIso:388, city:'Montego Bay',  name:'Sangster Intl',          lat:18.50, lon:-77.91, hubLevel:2, demand:2600, demandProfile:'TOURISM' },
    { id:'HAV', countryIso:192, city:'Havana',       name:'José Martí Intl',        lat:22.99, lon:-82.41, hubLevel:2, demand:2100, demandProfile:'LEISURE_SURGE' },
    // Europe — extended
    { id:'CPH', countryIso:208, city:'Copenhagen',   name:'Kastrup Airport',        lat:55.62, lon:12.66,  hubLevel:3, demand:4100, demandProfile:'BUSINESS' },
    { id:'HEL', countryIso:246, city:'Helsinki',     name:'Helsinki-Vantaa',        lat:60.32, lon:24.97,  hubLevel:3, demand:3400, demandProfile:'TRANSIT_HUB' },
    { id:'VIE', countryIso:40,  city:'Vienna',       name:'Vienna Intl Airport',    lat:48.11, lon:16.57,  hubLevel:3, demand:3800, demandProfile:'BUSINESS' },
    { id:'BRU', countryIso:56,  city:'Brussels',     name:'Brussels Airport',       lat:50.90, lon:4.48,   hubLevel:3, demand:3600, demandProfile:'BUSINESS' },
    { id:'ZRH', countryIso:756, city:'Zürich',       name:'Zürich Airport',         lat:47.46, lon:8.55,   hubLevel:4, demand:4200, demandProfile:'HIGH_YIELD' },
    { id:'GVA', countryIso:756, city:'Geneva',       name:'Geneva Intl Airport',    lat:46.24, lon:6.11,   hubLevel:3, demand:3200, demandProfile:'HIGH_YIELD' },
    { id:'LIS', countryIso:620, city:'Lisbon',       name:'Humberto Delgado Intl',  lat:38.78, lon:-9.14,  hubLevel:3, demand:3900, demandProfile:'TOURISM' },
    { id:'OPO', countryIso:620, city:'Porto',        name:'Francisco de Sá Carneiro',lat:41.24,lon:-8.68,  hubLevel:2, demand:2800, demandProfile:'TOURISM' },
    { id:'ATH', countryIso:300, city:'Athens',       name:'Eleftherios Venizelos',  lat:37.94, lon:23.95,  hubLevel:3, demand:3700, demandProfile:'TOURISM' },
    { id:'DUB', countryIso:372, city:'Dublin',       name:'Dublin Airport',         lat:53.42, lon:-6.27,  hubLevel:3, demand:3500, demandProfile:'TRANSIT_HUB' },
    { id:'OSL', countryIso:578, city:'Oslo',         name:'Gardermoen Airport',     lat:60.20, lon:11.08,  hubLevel:3, demand:3300, demandProfile:'BUSINESS' },
    { id:'PMI', countryIso:724, city:'Palma',        name:'Palma de Mallorca Intl', lat:39.55, lon:2.74,   hubLevel:3, demand:4400, demandProfile:'LEISURE_SURGE' },
    { id:'NAP', countryIso:380, city:'Naples',       name:'Capodichino Airport',    lat:40.88, lon:14.29,  hubLevel:2, demand:2900, demandProfile:'TOURISM' },
    { id:'VCE', countryIso:380, city:'Venice',       name:'Marco Polo Airport',     lat:45.50, lon:12.36,  hubLevel:2, demand:3100, demandProfile:'TOURISM' },
    { id:'TXL', countryIso:276, city:'Berlin',       name:'Brandenburg Airport',    lat:52.37, lon:13.52,  hubLevel:4, demand:4800, demandProfile:'BUSINESS' },
    { id:'HAM', countryIso:276, city:'Hamburg',      name:'Hamburg Airport',        lat:53.63, lon:10.00,  hubLevel:3, demand:3400, demandProfile:'BUSINESS' },
    { id:'BUD', countryIso:348, city:'Budapest',     name:'Ferenc Liszt Intl',      lat:47.43, lon:19.26,  hubLevel:3, demand:3200, demandProfile:'TOURISM' },
    { id:'PRG', countryIso:203, city:'Prague',       name:'Václav Havel Airport',   lat:50.10, lon:14.26,  hubLevel:3, demand:3600, demandProfile:'TOURISM' },
    { id:'OTP', countryIso:642, city:'Bucharest',    name:'Henri Coandă Intl',      lat:44.57, lon:26.10,  hubLevel:3, demand:3000, demandProfile:'EMERGING' },
    { id:'KBP', countryIso:804, city:'Kyiv',         name:'Boryspil Intl',          lat:50.34, lon:30.89,  hubLevel:3, demand:2800, demandProfile:'VOLATILE' },
    { id:'RIX', countryIso:428, city:'Riga',         name:'Riga Intl Airport',      lat:56.92, lon:23.97,  hubLevel:2, demand:2100, demandProfile:'TRANSIT_HUB' },
    { id:'VNO', countryIso:440, city:'Vilnius',      name:'Vilnius Airport',        lat:54.63, lon:25.29,  hubLevel:2, demand:1900, demandProfile:'EMERGING' },
    { id:'TLL', countryIso:233, city:'Tallinn',      name:'Lennart Meri Tallinn',   lat:59.41, lon:24.83,  hubLevel:2, demand:1800, demandProfile:'EMERGING' },
    { id:'KEF', countryIso:352, city:'Reykjavik',    name:'Keflavik Intl Airport',  lat:63.99, lon:-22.62, hubLevel:2, demand:2600, demandProfile:'TOURISM' },
    { id:'SKG', countryIso:300, city:'Thessaloniki', name:'Makedonia Airport',      lat:40.52, lon:22.97,  hubLevel:2, demand:2200, demandProfile:'TOURISM' },
    { id:'SOF', countryIso:100, city:'Sofia',        name:'Sofia Airport',          lat:42.69, lon:23.41,  hubLevel:2, demand:2100, demandProfile:'EMERGING' },
    { id:'LJU', countryIso:705, city:'Ljubljana',    name:'Jože Pučnik Airport',    lat:46.22, lon:14.46,  hubLevel:2, demand:1600, demandProfile:'BUSINESS' },
    { id:'ZAG', countryIso:191, city:'Zagreb',       name:'Franjo Tuđman Airport',  lat:45.74, lon:16.07,  hubLevel:2, demand:1800, demandProfile:'TOURISM' },
    { id:'BEG', countryIso:688, city:'Belgrade',     name:'Nikola Tesla Airport',   lat:44.82, lon:20.29,  hubLevel:2, demand:2000, demandProfile:'EMERGING' },
    { id:'SKP', countryIso:807, city:'Skopje',       name:'Alexander the Great',    lat:41.96, lon:21.62,  hubLevel:2, demand:1500, demandProfile:'EMERGING' },
    { id:'TIA', countryIso:8,   city:'Tirana',       name:'Nënë Tereza Intl',       lat:41.42, lon:19.72,  hubLevel:2, demand:1600, demandProfile:'EMERGING' },
    // Middle East — extended
    { id:'AMM', countryIso:400, city:'Amman',        name:'Queen Alia Intl',        lat:31.72, lon:35.99,  hubLevel:3, demand:3800, demandProfile:'TRANSIT_HUB' },
    { id:'KWI', countryIso:414, city:'Kuwait City',  name:'Kuwait Intl Airport',    lat:29.23, lon:47.97,  hubLevel:3, demand:3600, demandProfile:'BUSINESS' },
    { id:'BAH', countryIso:48,  city:'Manama',       name:'Bahrain Intl Airport',   lat:26.27, lon:50.63,  hubLevel:3, demand:3200, demandProfile:'BUSINESS' },
    { id:'MCT', countryIso:512, city:'Muscat',       name:'Muscat Intl Airport',    lat:23.59, lon:58.28,  hubLevel:3, demand:3400, demandProfile:'BUSINESS' },
    { id:'TLV', countryIso:376, city:'Tel Aviv',     name:'Ben Gurion Airport',     lat:32.01, lon:34.89,  hubLevel:4, demand:4600, demandProfile:'HIGH_YIELD' },
    { id:'BEY', countryIso:422, city:'Beirut',       name:'Rafic Hariri Intl',      lat:33.82, lon:35.49,  hubLevel:3, demand:2800, demandProfile:'VOLATILE' },
    { id:'BGW', countryIso:368, city:'Baghdad',      name:'Baghdad Intl Airport',   lat:33.26, lon:44.23,  hubLevel:2, demand:2200, demandProfile:'VOLATILE' },
    { id:'THR', countryIso:364, city:'Tehran',       name:'Imam Khomeini Intl',     lat:35.41, lon:51.15,  hubLevel:3, demand:3000, demandProfile:'VOLATILE' },
    { id:'KHI', countryIso:586, city:'Karachi',      name:'Jinnah Intl Airport',    lat:24.90, lon:67.16,  hubLevel:3, demand:3200, demandProfile:'EMERGING' },
    { id:'LHE', countryIso:586, city:'Lahore',       name:'Allama Iqbal Intl',      lat:31.52, lon:74.40,  hubLevel:2, demand:2600, demandProfile:'EMERGING' },
    { id:'ISB', countryIso:586, city:'Islamabad',    name:'Islamabad Intl Airport', lat:33.56, lon:72.85,  hubLevel:2, demand:2300, demandProfile:'BUSINESS' },
    // Africa — extended
    { id:'ACC', countryIso:288, city:'Accra',        name:'Kotoka Intl Airport',    lat:5.60,  lon:-0.17,  hubLevel:3, demand:2800, demandProfile:'EMERGING' },
    { id:'DKR', countryIso:686, city:'Dakar',        name:'Blaise Diagne Intl',     lat:14.74, lon:-17.49, hubLevel:2, demand:2000, demandProfile:'EMERGING' },
    { id:'ABV', countryIso:566, city:'Abuja',        name:'Nnamdi Azikiwe Intl',    lat:9.01,  lon:7.26,   hubLevel:3, demand:2600, demandProfile:'BUSINESS' },
    { id:'TUN', countryIso:788, city:'Tunis',        name:'Tunis-Carthage Intl',    lat:36.85, lon:10.23,  hubLevel:2, demand:2200, demandProfile:'TOURISM' },
    { id:'ALG', countryIso:12,  city:'Algiers',      name:'Houari Boumediene Intl', lat:36.69, lon:3.22,   hubLevel:3, demand:2500, demandProfile:'BUSINESS' },
    { id:'TRP', countryIso:434, city:'Tripoli',      name:'Mitiga Airport',         lat:32.89, lon:13.28,  hubLevel:2, demand:1600, demandProfile:'VOLATILE' },
    { id:'HRE', countryIso:716, city:'Harare',       name:'Robert Gabriel Mugabe',  lat:-17.93,lon:31.09,  hubLevel:2, demand:1800, demandProfile:'VOLATILE' },
    { id:'LLW', countryIso:454, city:'Lilongwe',     name:'Kamuzu Intl Airport',    lat:-13.79,lon:33.78,  hubLevel:2, demand:1400, demandProfile:'EMERGING' },
    { id:'WDH', countryIso:516, city:'Windhoek',     name:'Hosea Kutako Intl',      lat:-22.48,lon:17.47,  hubLevel:2, demand:1700, demandProfile:'TOURISM' },
    { id:'MBA', countryIso:404, city:'Mombasa',      name:'Moi Intl Airport',       lat:-4.03, lon:39.59,  hubLevel:2, demand:2100, demandProfile:'TOURISM' },
    { id:'DAR', countryIso:834, city:'Dar es Salaam',name:'Julius Nyerere Intl',    lat:-6.88, lon:39.20,  hubLevel:2, demand:2200, demandProfile:'EMERGING' },
    { id:'EBB', countryIso:800, city:'Entebbe',      name:'Entebbe Intl Airport',   lat:0.04,  lon:32.44,  hubLevel:2, demand:1900, demandProfile:'EMERGING' },
    { id:'KGL', countryIso:646, city:'Kigali',       name:'Kigali Intl Airport',    lat:-1.97, lon:30.14,  hubLevel:2, demand:1800, demandProfile:'GROWING' },
    { id:'MRU', countryIso:480, city:'Mauritius',    name:'Sir Seewoosagur Ramgoolam',lat:-20.43,lon:57.68,hubLevel:2, demand:2400, demandProfile:'TOURISM' },
    { id:'TNR', countryIso:450, city:'Antananarivo', name:'Ivato Intl Airport',     lat:-18.80,lon:47.48,  hubLevel:2, demand:1600, demandProfile:'SAFARI_NICHE' },
    { id:'MPM', countryIso:508, city:'Maputo',       name:'Maputo Intl Airport',    lat:-25.92,lon:32.57,  hubLevel:2, demand:1500, demandProfile:'EMERGING' },
    { id:'LFW', countryIso:768, city:'Lomé',         name:'Gnassingbé Eyadéma Intl',lat:6.17,  lon:1.25,   hubLevel:2, demand:1400, demandProfile:'EMERGING' },
    { id:'OUA', countryIso:854, city:'Ouagadougou',  name:'Ouagadougou Airport',    lat:12.35, lon:-1.51,  hubLevel:2, demand:1300, demandProfile:'VOLATILE' },
    { id:'BKO', countryIso:466, city:'Bamako',       name:'Modibo Keïta Intl',      lat:12.53, lon:-7.95,  hubLevel:2, demand:1400, demandProfile:'VOLATILE' },
    { id:'DLA', countryIso:120, city:'Douala',       name:'Douala Intl Airport',    lat:4.01,  lon:9.72,   hubLevel:2, demand:1800, demandProfile:'EMERGING' },
    { id:'LBV', countryIso:266, city:'Libreville',   name:'Léon-Mba Intl Airport',  lat:0.46,  lon:9.41,   hubLevel:2, demand:1600, demandProfile:'BUSINESS' },
    { id:'FIH', countryIso:180, city:'Kinshasa',     name:'N\'djili Airport',       lat:-4.39, lon:15.44,  hubLevel:2, demand:1900, demandProfile:'VOLATILE' },
    { id:'LAD', countryIso:24,  city:'Luanda',       name:'Quatro de Fevereiro',    lat:-8.86, lon:13.23,  hubLevel:3, demand:2400, demandProfile:'BUSINESS' },
    { id:'LUN', countryIso:894, city:'Lusaka',       name:'Kenneth Kaunda Intl',    lat:-15.33,lon:28.45,  hubLevel:2, demand:1700, demandProfile:'EMERGING' },
    // Asia — extended
    { id:'HYD', countryIso:356, city:'Hyderabad',    name:'Rajiv Gandhi Intl',      lat:17.23, lon:78.43,  hubLevel:3, demand:4200, demandProfile:'TECH_BUSINESS' },
    { id:'MAA', countryIso:356, city:'Chennai',      name:'Chennai Intl Airport',   lat:12.99, lon:80.18,  hubLevel:3, demand:3800, demandProfile:'TECH_BUSINESS' },
    { id:'CCU', countryIso:356, city:'Kolkata',      name:'Netaji Subhash Chandra Bose',lat:22.65,lon:88.45,hubLevel:3, demand:3400, demandProfile:'LARGE_DOMESTIC' },
    { id:'AMD', countryIso:356, city:'Ahmedabad',    name:'Sardar Vallabhbhai Patel',lat:23.07,lon:72.63,  hubLevel:2, demand:2800, demandProfile:'BUSINESS' },
    { id:'COK', countryIso:356, city:'Kochi',        name:'Cochin Intl Airport',    lat:10.15, lon:76.40,  hubLevel:2, demand:2400, demandProfile:'LARGE_DOMESTIC' },
    { id:'CTU', countryIso:156, city:'Chengdu',      name:'Tianfu Intl Airport',    lat:30.31, lon:103.95, hubLevel:4, demand:5800, demandProfile:'EXPLOSIVE' },
    { id:'HGH', countryIso:156, city:'Hangzhou',     name:'Xiaoshan Intl Airport',  lat:30.23, lon:120.43, hubLevel:3, demand:4200, demandProfile:'TECH_BUSINESS' },
    { id:'WUH', countryIso:156, city:'Wuhan',        name:'Tianhe Intl Airport',    lat:30.78, lon:114.21, hubLevel:3, demand:4500, demandProfile:'GROWING' },
    { id:'XIY', countryIso:156, city:"Xi'an",        name:'Xianyang Intl Airport',  lat:34.45, lon:108.75, hubLevel:3, demand:4000, demandProfile:'TOURISM' },
    { id:'KMG', countryIso:156, city:'Kunming',      name:'Changshui Intl Airport', lat:25.11, lon:102.93, hubLevel:3, demand:3800, demandProfile:'TOURISM' },
    { id:'URC', countryIso:156, city:'Ürümqi',       name:'Diwopu Intl Airport',    lat:43.91, lon:87.47,  hubLevel:2, demand:2500, demandProfile:'EMERGING' },
    { id:'CKG', countryIso:156, city:'Chongqing',    name:'Jiangbei Intl Airport',  lat:29.72, lon:106.64, hubLevel:4, demand:5200, demandProfile:'EXPLOSIVE' },
    { id:'CSX', countryIso:156, city:'Changsha',     name:'Huanghua Intl Airport',  lat:28.19, lon:113.22, hubLevel:3, demand:3600, demandProfile:'GROWING' },
    { id:'NKG', countryIso:156, city:'Nanjing',      name:'Lukou Intl Airport',     lat:31.74, lon:118.87, hubLevel:3, demand:3900, demandProfile:'BUSINESS' },
    { id:'SHE', countryIso:156, city:'Shenyang',     name:'Taoxian Intl Airport',   lat:41.64, lon:123.49, hubLevel:3, demand:3200, demandProfile:'LARGE_DOMESTIC' },
    { id:'HKG', countryIso:344, city:'Hong Kong',    name:'Hong Kong Intl Airport', lat:22.31, lon:113.92, hubLevel:5, demand:8800, demandProfile:'ULTRA_HIGH' },
    { id:'MFM', countryIso:446, city:'Macau',        name:'Macau Intl Airport',     lat:22.15, lon:113.59, hubLevel:2, demand:2200, demandProfile:'LEISURE_SURGE' },
    { id:'TPE', countryIso:158, city:'Taipei',       name:'Taiwan Taoyuan Intl',    lat:25.08, lon:121.23, hubLevel:4, demand:5800, demandProfile:'TECH_BUSINESS' },
    { id:'CTS', countryIso:392, city:'Sapporo',      name:'New Chitose Airport',    lat:42.78, lon:141.69, hubLevel:3, demand:3400, demandProfile:'TOURISM' },
    { id:'OKA', countryIso:392, city:'Okinawa',      name:'Naha Airport',           lat:26.19, lon:127.65, hubLevel:2, demand:2800, demandProfile:'TOURISM' },
    { id:'FUK', countryIso:392, city:'Fukuoka',      name:'Fukuoka Airport',        lat:33.59, lon:130.45, hubLevel:3, demand:3600, demandProfile:'BUSINESS' },
    { id:'NGO', countryIso:392, city:'Nagoya',       name:'Chubu Centrair Intl',    lat:34.86, lon:136.81, hubLevel:3, demand:3800, demandProfile:'TECH_BUSINESS' },
    { id:'GMP', countryIso:410, city:'Seoul',        name:'Gimpo Intl Airport',     lat:37.56, lon:126.79, hubLevel:4, demand:5200, demandProfile:'BUSINESS' },
    { id:'PUS', countryIso:410, city:'Busan',        name:'Gimhae Intl Airport',    lat:35.18, lon:128.94, hubLevel:3, demand:3200, demandProfile:'BUSINESS' },
    { id:'RGN', countryIso:104, city:'Yangon',       name:'Hanthawaddy Intl',       lat:16.90, lon:96.13,  hubLevel:2, demand:2000, demandProfile:'EMERGING' },
    { id:'REP', countryIso:116, city:'Siem Reap',    name:'Angkor Intl Airport',    lat:13.41, lon:103.81, hubLevel:2, demand:2400, demandProfile:'TOURISM' },
    { id:'VTE', countryIso:418, city:'Vientiane',    name:'Wattay Intl Airport',    lat:17.99, lon:102.56, hubLevel:2, demand:1600, demandProfile:'EMERGING' },
    { id:'PNH', countryIso:116, city:'Phnom Penh',   name:'Phnom Penh Intl',        lat:11.55, lon:104.84, hubLevel:2, demand:1800, demandProfile:'EMERGING' },
    { id:'CMB', countryIso:144, city:'Colombo',      name:'Bandaranaike Intl',      lat:7.18,  lon:79.88,  hubLevel:3, demand:3100, demandProfile:'TOURISM' },
    { id:'DAC', countryIso:50,  city:'Dhaka',        name:'Hazrat Shahjalal Intl',  lat:23.84, lon:90.40,  hubLevel:3, demand:3300, demandProfile:'LARGE_DOMESTIC' },
    { id:'KTM', countryIso:524, city:'Kathmandu',    name:'Tribhuvan Intl Airport', lat:27.70, lon:85.36,  hubLevel:2, demand:2100, demandProfile:'TOURISM' },
    { id:'MLE', countryIso:462, city:'Malé',         name:'Velana Intl Airport',    lat:4.19,  lon:73.53,  hubLevel:2, demand:2600, demandProfile:'TOURISM' },
    { id:'AKL', countryIso:554, city:'Auckland',     name:'Auckland Airport',       lat:-37.01,lon:174.79, hubLevel:4, demand:5200, demandProfile:'TOURISM' },
    { id:'CHC', countryIso:554, city:'Christchurch', name:'Christchurch Airport',   lat:-43.49,lon:172.54, hubLevel:2, demand:2800, demandProfile:'TOURISM' },
    { id:'BNE', countryIso:36,  city:'Brisbane',     name:'Brisbane Airport',       lat:-27.38,lon:153.12, hubLevel:3, demand:4200, demandProfile:'TOURISM' },
    { id:'PER', countryIso:36,  city:'Perth',        name:'Perth Airport',          lat:-31.94,lon:115.97, hubLevel:3, demand:3800, demandProfile:'MIXED' },
    { id:'ADL', countryIso:36,  city:'Adelaide',     name:'Adelaide Airport',       lat:-34.95,lon:138.53, hubLevel:2, demand:2900, demandProfile:'BUSINESS' },
    { id:'GUM', countryIso:316, city:'Guam',         name:'Antonio B Won Pat Intl', lat:13.48, lon:144.80, hubLevel:2, demand:1900, demandProfile:'TOURISM' },
    { id:'PPT', countryIso:258, city:'Papeete',      name:'Faa\'a Intl Airport',    lat:-17.55,lon:-149.61,hubLevel:2, demand:1800, demandProfile:'TOURISM' },
    { id:'SUB', countryIso:360, city:'Surabaya',     name:'Juanda Intl Airport',    lat:-7.38, lon:112.79, hubLevel:3, demand:3600, demandProfile:'GROWING' },
    { id:'UPG', countryIso:360, city:'Makassar',     name:'Sultan Hasanuddin Intl', lat:-5.06, lon:119.55, hubLevel:2, demand:2400, demandProfile:'GROWING' },
    { id:'MDC', countryIso:360, city:'Manado',       name:'Sam Ratulangi Intl',     lat:1.55,  lon:124.93, hubLevel:2, demand:1700, demandProfile:'ARCHIPELAGO' },
    { id:'PEN', countryIso:458, city:'Penang',       name:'Penang Intl Airport',    lat:5.30,  lon:100.28, hubLevel:2, demand:2400, demandProfile:'TOURISM' },
    { id:'BKI', countryIso:458, city:'Kota Kinabalu',name:'Kota Kinabalu Intl',     lat:5.94,  lon:116.05, hubLevel:2, demand:2200, demandProfile:'TOURISM' },
    // Central Asia
    { id:'ALA', countryIso:398, city:'Almaty',       name:'Almaty Intl Airport',    lat:43.35, lon:77.04,  hubLevel:3, demand:2600, demandProfile:'EMERGING' },
    { id:'TAS', countryIso:860, city:'Tashkent',     name:'Islam Karimov Intl',     lat:41.26, lon:69.28,  hubLevel:2, demand:2100, demandProfile:'EMERGING' },
    { id:'FRU', countryIso:417, city:'Bishkek',      name:'Manas Intl Airport',     lat:43.06, lon:74.48,  hubLevel:2, demand:1600, demandProfile:'EMERGING' },
    { id:'ASB', countryIso:795, city:'Ashgabat',     name:'Ashgabat Intl Airport',  lat:37.99, lon:58.36,  hubLevel:2, demand:1400, demandProfile:'VOLATILE' },
    { id:'DYU', countryIso:762, city:'Dushanbe',     name:'Dushanbe Intl Airport',  lat:38.54, lon:68.82,  hubLevel:2, demand:1300, demandProfile:'VOLATILE' },
    { id:'EVN', countryIso:51,  city:'Yerevan',      name:'Zvartnots Intl Airport', lat:40.15, lon:44.40,  hubLevel:2, demand:1800, demandProfile:'EMERGING' },
    { id:'GYD', countryIso:31,  city:'Baku',         name:'Heydar Aliyev Intl',     lat:40.47, lon:50.05,  hubLevel:3, demand:2800, demandProfile:'BUSINESS' },
    { id:'TBS', countryIso:268, city:'Tbilisi',      name:'Shota Rustaveli Intl',   lat:41.67, lon:44.95,  hubLevel:2, demand:2000, demandProfile:'TOURISM' },
  ],

  // ── NPC AIRLINE ROUTES ────────────────────────────────────
  // Background flights that animate on the map (world air traffic)
  npcRoutes: [
    ['LHR','JFK'],['CDG','DXB'],['FRA','PEK'],['AMS','SIN'],['IST','BOM'],
    ['DXB','SYD'],['SIN','NRT'],['JFK','LAX'],['LHR','CDG'],['FRA','JFK'],
    ['PEK','LAX'],['SIN','DXB'],['NRT','LAX'],['ICN','SFO'],['DOH','LHR'],
    ['GRU','LHR'],['JNB','DXB'],['BKK','SIN'],['MNL','NRT'],['DEL','DXB'],
    ['SVO','FRA'],['MAD','CDG'],['IST','CAI'],['SYD','SIN'],['LOS','LHR'],
    ['ORD','LHR'],['MIA','GRU'],['YYZ','LHR'],['ADD','DXB'],['CMN','CDG'],
  ],

  // ── DISTANCE BANDS ────────────────────────────────────────
  distanceBands: {
    SHORT:  { label:'Short Haul',  maxKm:2500,  fuelMult:1.0, crewMult:1.0 },
    MEDIUM: { label:'Medium Haul', maxKm:6000,  fuelMult:1.4, crewMult:1.2 },
    LONG:   { label:'Long Haul',   maxKm:12000, fuelMult:2.0, crewMult:1.6 },
    ULTRA:  { label:'Ultra Long',  maxKm:99999, fuelMult:2.8, crewMult:2.2 },
  },
};

// ── GEO UTILITIES ─────────────────────────────────────────
window.SkyHigh.GeoUtils = {
  distance(lat1, lon1, lat2, lon2) {
    const R = 6371;
    const dLat = (lat2-lat1)*Math.PI/180;
    const dLon = (lon2-lon1)*Math.PI/180;
    const a = Math.sin(dLat/2)**2 + Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLon/2)**2;
    return R*2*Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
  },
  getDistanceBand(km) {
    const b = SkyHigh.MAP_DATA.distanceBands;
    if (km<=b.SHORT.maxKm) return 'SHORT';
    if (km<=b.MEDIUM.maxKm) return 'MEDIUM';
    if (km<=b.LONG.maxKm) return 'LONG';
    return 'ULTRA';
  },
  getAirport(id) { return SkyHigh.MAP_DATA.airports.find(a=>a.id===id); },
  getAirportsByCountryIso(iso) { return SkyHigh.MAP_DATA.airports.filter(a=>a.countryIso===iso); },
};
